/**
 * Project Euler -- Problem 002
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
#include <iostream>

auto compute_answer() {
    long int p0 = 1;
    long int p1 = 2;
    long int acc = 0;

    while (p1 <= 4000000) {
        acc += (p1 % 2 == 0) ? p1 : 0;
        auto tmp = p0 + p1;
        p0 = p1;
        p1 = tmp;
    }

    return acc;
}

int main(int argc, char **argv) {
    std::cout << compute_answer() << std::endl;
    return 0;
}
